-keep class com.awesomeproject.DndModule { *; }
-keep class com.awesomeproject.DndPackage { *; }
-keep class com.facebook.react.bridge.** { *; }
-keep class com.facebook.react.HeadlessJsTaskService { *; }
-keep class app.notifee.** { *; }
-dontwarn app.notifee.**